services:
  oracle-db:
    build:
      context: .
    container_name: ecommerce-oracle-db
    ports:
      - "1521:1521"
      - "1522:1522"
      - "8443:8443"
    environment:
      WORKLOAD_TYPE: ${WORKLOAD_TYPE:-ATP}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
    cap_add:
      - SYS_ADMIN
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - oracle_data:/u01/app/oracle/oradata
    shm_size: 1gb
    tmpfs:
      - /dev/shm

volumes:
  oracle_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
